name: Check Code Style

on: [pull_request, push]

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Setup python
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: flake8
      run: |
        flake8 usr/cmd/connstat usr/test/connstat_unittest.py --show-source --statistics
